USE Entrega

CREATE TABLE Envio (
Cod_Envio INT NOT NULL PRIMARY KEY,
DataEnvio DATE NOT NULL,
NomeEnvio NVARCHAR(70) NOT NULL,
Frete DECIMAL(6,2) NOT NULL,
Cidade NVARCHAR(70) NOT NULL,
Regiao NVARCHAR(60) NOT NULL,
Pais NVARCHAR(40) NOT NULL,
Cod_Categoria INT NOT NULL,  
CONSTRAINT FK_Envio_Categoria FOREIGN KEY (Cod_Categoria) REFERENCES Categoria(Cod_Categoria)
);

GO